spring:
  datasource:
    url: jdbc:mysql://localhost:3306/six_degrees?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true
    username: sixuser
    password: "six123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true